### ISSUE TITLE
How to use custom React components with Rum?

### ISSUE THREAD

**Issue by dovalid** [zgendao/incognito-community-landing#1]
(heroAnim branch)

Próbálom használni ezt a libraryt, hogy ne kelljen hiccuppá alakítani az svg-t és spamelni vele a kódot: https://www.npmjs.com/package/react-samy-svg

A heroArt_.cljs-be beraktam ahogy a leírás alapján gondolnám hogy használni kell, de ezt az errort dobja:
![image](https://user-images.githubusercontent.com/38188141/86964063-c8074a00-c165-11ea-906b-60f6244a0f46.png)

Ami ugye nem segít mert nagybetűvel kezdtem. Végigolvastam a Rum doksit de nem jöttem rá hogy mit csinálok rosszul. Hogy kéne?

**Comment by liszper** [comment]
Nem tudtam branch-re pusholni, igy kiment masterre, de meg van.

A javascriptes React.createElement fuggvennyel tudtam megoldani.

**Comment by dovalid** [comment]
A defeket még mindig figyelmen kívül hagyja valamiért, ugye már nem az a probléma hogy kisbetűs a lineargradient pl. Nem tudtam vele mit csinálni, úgyhogy átmásoltam őket az index.html-be, így működik, csak csúnya megoldás. De valszeg az svg miatt van, mert css based style tageket használ, ezesetben viszont felesleges vele tovább szarakodni. Majd legközelebb már lesz rendes tool ami rendes svgt generál, és úgy remélhetőleg nem lesz már ilyen probléma.
